### ISSUE TITLE
Plotting Figure 2

### ISSUE THREAD

**Issue by sopeeweje** [sopeeweje/NLP-AI-Diagnosis#8]
Figure 2 looks at funding growth by cluster, grouped by clinical vs. technical applications of AI. 
![image](https://user-images.githubusercontent.com/58275563/135777762-1e616cc0-844c-4948-9e57-1ead4c9e6207.png)

This is the function that plots it:
https://github.com/sopeeweje/NLP-AI-Medicine/blob/bfe01bf1ba44b215b88ec402cd0c1a5a4e15f377/random_plotting.py#L181-L257

End goal: have this function accept a result directory as an input and output the figure. As a bonus, figure out a better way of denoting the clinical vs. technical applications than red vs. blue. This can be put in a file separate from analyze_clusters.py called "plotting.py" (will need to sort through the necessary imports and all that good stuff)

The "final_data.csv" file in each directory given to this function will have to be edited to include two columns:
1. "Description" - phrase used to describe the cluster (ex. Cancer genomics)
2. "Category" - category of a group of clusters (ex. Genetics)

Assume that these will be input into the CSV at the same column index each time.

**Comment by sb1024** [comment]
Do you want Rajat to edit analyze_clusters.py to add the two columns to final_data.csv? Also would you be okay with me merging my changes into main because I've made some changes to final_data.csv as well -- and we want Rajat's changes to be on top of those.

**Comment by sopeeweje** [comment]
Either one of you can (goes with #2), and definitely good with merging

**Comment by sb1024** [comment]
Actually we realized that it's probably better to have him add the columns to final_data separately since the columns are handmade. Do you want him to pull the description/category from Table 1 in your draft? And can you confirm the result folder that these are from just so he is using the right one?

**Comment by sopeeweje** [comment]
Oh sorry just to clarify - just add space for the info to be entered in those columns. Descriptions/categories for when he's testing the plotting functions doesn't matter, just do whatever for now (can use the descriptions from Table 1 if you want). The functions should be able to accept any result folder

**Comment by sb1024** [comment]
Ok so I'll just add headers for those columns with empty values. Since the descriptions are handmade though, should we just assume they will be present in the result folder?

**Comment by rajat-chandra** [comment]
I do not see graph_projections function being called anywhere, do you have a test script that I can use to see if my changes work as expected? I can also write my own, thanks!

**Comment by sopeeweje** [comment]
@sb1024 Yes you can make that assumption

@rajat-chandra it isn't called anywhere, you can put it in a standalone script

**Comment by rajat-chandra** [comment]
I tried to address issues 8 and 9 in this pull request: https://github.com/sopeeweje/NLP-AI-Medicine/pull/11/files

A few questions / comments:
1. The graph_projections and plot_translation_metrics functions assume that columns indexed at 16 and 17 of final_data.csv are "Description" and "Category", respectively, as is the case in 07-18-2021--132946
2. The png files that I saved do not retain the nicer formatting of the plot that pops up when running the functions. I think it would be better to use the plot that pops up for the paper rather than the png, and I can try reformatting the plot being saved as a png when using the final data if that makes sense as well.
3. The "actual_vs_projected.png" being created here has a lot of (crowded) annotations that the original graph does not, should these annotations be kept or should I remove the code for them?
4. I modified the functions in "random_plotting.py" itself. Should I create a new "plotting.py" that has just the graph_projections and plot_translation_metrics functions?
5. I am not yet sure of a better way than the red and blue to divide clinical vs technical but I can keep thinking about it and let you know if I come up with anything
6. The 07-18-2021--132946/final_data.csv includes some categories that are "N/A" that I ignored for testing purposes and may have resulted in some formatting issues, but I assume that none of the 60 clusters will have "N/A" for the category for the final data. Please let me know if this is not the case

If everything looks okay I can merge the changes in. Thank you!
